version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
 listener:
   image: ubuntu:trusty
   ports:
     - "4444:4444"
   command: ['/dest/listener', '-p 4444', '-c']
   dev_overrides:
     environment:
       - "DEBUG=1"

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   
